server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8

spring:
  data:
    mongodb:
      uri: 'mongodb://root:rootpassword@mongodb:27017/admin'
      username: root
      password: rootpassword
      database: admin
      host: localhost
      port: 27017
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,httptrace,threaddump,scheduledtasks,metrics,mappings,beans