version: "2.1"
services:
  app:
    image: openjdk:17-jdk
    mem_limit: 4G
    volumes:
      - ./target/backend-1.jar:/app/service.jar
    environment:
      - TZ=UTC
      - SPRING_PROFILES_ACTIVE=local
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: java -jar /app/service.jar
